name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          cd PJCFront
          npm install
          npm run build

      - name: Build backend
        run: |
          cd PJCBack
          go build -o backend main.go

      - name: Deploy to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
          scp -r PJCFront/dist ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/var/www/pjcorsun
          scp PJCBack/backend ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/var/www/pjcorsun/backend
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "sudo systemctl restart pjcorsun-backend"
